var data =
{
    "singers": [
        {
            "firstname": "Spence",
            "lastname": "Hood",
            "vocalpart": "Tenor I"
        },
        {
            "firstname": "Evan",
            "lastname": "Oliver",
            "vocalpart": "Tenor I"
        },
        {
            "firstname": "John",
            "lastname": "Piccone",
            "vocalpart": "Tenor I"
        },
        {
            "firstname": "Tim",
            "lastname": "Dolquist",
            "vocalpart": "Tenor II"
        },
        {
            "firstname": "Andy",
            "lastname": "Seracuse",
            "vocalpart": "Tenor II"
        },
        {
            "firstname": "Max",
            "lastname": "Sendor",
            "vocalpart": "Tenor II"
        },
        {
            "firstname": "Kevin",
            "lastname": "O'Connor",
            "vocalpart": "Baritone"
        },
        {
            "firstname": "Tyler",
            "lastname": "Polen",
            "vocalpart": "Baritone"
        },
        {
            "firstname": "Ian",
            "lastname": "Collett",
            "vocalpart": "Bass"
        },
        {
            "firstname": "Peter",
            "lastname": "Hassinger",
            "vocalpart": "Bass"
        },
        {
            "firstname": "Kevin",
            "lastname": "Bell",
            "vocalpart": "Bass"
        },

    ], "songs": [
        {
            "title": "Africa",
            "arranger": "Unknown",
            "key": "G",
            "firstchord": "G",
            "soloist": null,
            "understudy": null,
            "duetist": "Evan Oliver",
            "duetunderstudy": "Spence Hood",
            "beatboxer": "Andy Seracuse",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Stars Go Blue",
            "arranger": "Unknown",
            "key": "G",
            "firstchord": "C",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Shiver Shiver",
            "arranger": "David Bashford",
            "key": "Ab",
            "firstchord": "Ab",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Sexual Healing",
            "arranger": "Unknown",
            "key": "Ab",
            "firstchord": "Eb",
            "soloist": "Kevin Bell",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Spence Hood",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": false,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "For The Longest Time",
            "arranger": "Unknown",
            "key": "Bb",
            "firstchord": "Bb",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Drift Away",
            "arranger": "Unknown",
            "key": "F",
            "firstchord": "Bb",
            "soloist": "Kevin Bell",
            "understudy": "John Piccone",
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Spence Hood",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Cecelia",
            "arranger": "Unknown",
            "key": "Bb",
            "firstchord": "Bb",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": false,
            "isgroup": true,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Landed",
            "arranger": "Unknown",
            "key": "Bb",
            "firstchord": "Bb",
            "soloist": "Evan Oliver",
            "understudy": "Tim Dolquist",
            "duetist": "Tim Dolquist",
            "duetunderstudy": "Spence Hood",
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": "Spence Hood",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Oh What A Night",
            "arranger": "David Bashford",
            "key": "Bb",
            "firstchord": "Bb",
            "soloist": "Spence Hood",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Andy Seracuse",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Shambala",
            "arranger": "Unknown",
            "key": "B",
            "firstchord": "B",
            "soloist": "Tim Dolquist",
            "understudy": null,
            "duetist": "Spence Hood",
            "duetunderstudy": null,
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": "Spence Hood",
            "isappropriate": true,
            "isgroup": true,
            "isxmas": false,
            "intros": ["Describe what shambala is/means, warm and fuzzy intro"]
        },
        {
            "title": "Runaround Sue",
            "arranger": "Unknown",
            "key": "B",
            "firstchord": "B",
            "soloist": "Kevin Bell",
            "understudy": null,
            "duetist": "Spence Hood",
            "duetunderstudy": "Evan Oliver",
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": ["Set it up like audience is about to hear a sad personal story about the soloist"]
        },
        {
            "title": "Seven Bridges Road",
            "arranger": "Unknown",
            "key": "C",
            "firstchord": "C",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": true,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "It's All Been Done",
            "arranger": "David Bashford",
            "key": "C",
            "firstchord": "C",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": "Spence Hood",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": ["If last song of set, make joke about the song title"]
        },
        {
            "title": "Heard It Through The Grapevine",
            "arranger": "Tim Dolquist",
            "key": "Cm",
            "firstchord": "Cm",
            "soloist": "John Piccone",
            "understudy": "Andy Seracuse",
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Tribute",
            "arranger": "Unknown",
            "key": "C",
            "firstchord": "C",
            "soloist": "Seniors",
            "understudy": "Juniors",
            "duetist": "Seniors",
            "duetunderstudy": "Juniors",
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": ["How meaningful Tribs is to the group, what the song represents", "We usually don't sing this at shows..."]
        },
        {
            "title": "Some Kind Of Wonderful",
            "arranger": "Unknown",
            "key": "Db",
            "firstchord": "Db",
            "soloist": "Andy Seracuse",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Spence Hood",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Blue Moon",
            "arranger": "Ben Pollack",
            "key": "Db",
            "firstchord": "Db",
            "soloist": "Andy Seracuse",
            "understudy": "John Piccone",
            "duetist": "Spence Hood",
            "duetunderstudy": "Peter Hassinger",
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": ["Do I put an orange in my beer? Once in a blue moon..."]
        },
        {
            "title": "Helplessness Blues",
            "arranger": "David Bashford",
            "key": "D",
            "firstchord": "D",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Mirrors",
            "arranger": "Spence Hood",
            "key": "D",
            "firstchord": "D",
            "soloist": "Spence Hood",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": ["Most modern song we do, a little different from everything else"]
        },
        {
            "title": "Short Skirt, Long Jacket",
            "arranger": "Kyle Donovan",
            "key": "D",
            "firstchord": "D",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Spence Hood",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": ["Some pun about cake"]
        },
        {
            "title": "Still Of The Night",
            "arranger": "Unknown",
            "key": "Eb",
            "firstchord": "Eb",
            "soloist": "Tim Dolquist",
            "understudy": null,
            "duetist": "Spence Hood",
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "To Be With You",
            "arranger": "Unknown",
            "key": "Eb",
            "firstchord": "Cm",
            "soloist": "Spence Hood",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Take Me To The River",
            "arranger": "Unknown",
            "key": "Eb",
            "firstchord": "Eb",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Spence Hood",
            "beatboxunderstudy": "Tim Dolquist",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Love You Madly",
            "arranger": "Unknown",
            "key": "Eb",
            "firstchord": "Eb",
            "soloist": null,
            "understudy": null,
            "duetist": "Spence Hood",
            "duetunderstudy": "Tim Dolquist",
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Go Your Own Way",
            "arranger": "David Bashford",
            "key": "Eb",
            "firstchord": "Eb",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": "Spence Hood",
            "isappropriate": true,
            "isgroup": true,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Signed, Sealed, Delivered",
            "arranger": "Unknown",
            "key": "E",
            "firstchord": "E",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": "Tim Dolquist",
            "beatboxunderstudy": "Spence Hood",
            "isappropriate": true,
            "isgroup": true,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Good Old A Cappella",
            "arranger": "Unknown",
            "key": "E",
            "firstchord": "E",
            "soloist": "Tim Dolquist",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "White Winter Hymnal",
            "arranger": "David Bashford",
            "key": "E",
            "firstchord": "E",
            "soloist": "Tim Dolquist",
            "understudy": "Spence Hood",
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": true,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Insomniac",
            "arranger": "Unknown",
            "key": "F",
            "firstchord": "F",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Tracks Of My Tears",
            "arranger": "Unknown",
            "key": "F",
            "firstchord": "F",
            "soloist": "Tim Dolquist",
            "understudy": null,
            "duetist": "Spence Hood",
            "duetunderstudy": null,
            "beatboxer": "Evan Oliver",
            "beatboxunderstudy": "Spence Hood",
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Let's Stay Together",
            "arranger": "Spence Hood",
            "key": "F",
            "firstchord": "F",
            "soloist": "Kevin Bell",
            "understudy": "Andy Seracuse",
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Georgia On My Mind",
            "arranger": "Oakleigh Thorne",
            "key": "F",
            "firstchord": "F",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": true,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Roll To Me",
            "arranger": "Unknown",
            "key": "Gb",
            "firstchord": "Gb",
            "soloist": "Spence Hood",
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Wonderful Tonight",
            "arranger": "Unknown",
            "key": "Gb",
            "firstchord": "Gb",
            "soloist": null,
            "understudy": null,
            "duetist": null,
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        },
        {
            "title": "Lost In A Moment",
            "arranger": "David Bashford",
            "key": "Gb",
            "firstchord": "Gb",
            "soloist": "Tim Dolquist",
            "understudy": null,
            "duetist": "Spence Hood",
            "duetunderstudy": null,
            "beatboxer": null,
            "beatboxunderstudy": null,
            "isappropriate": true,
            "isgroup": false,
            "isxmas": false,
            "intros": []
        }
    ]
}